name: "Tmate debugging tests"
description: "Setup tmate session if the test fails"
inputs:
  use-tmate:
    description: "boolean for enabling TMATE"
    required: false
  timeout-minutes:
    description: "timeout tmate debug session"
    required: false
    default: '60'
# ...name, description and inputs as above
runs:
  using: "composite"
  steps:
    - name: consider debugging
      shell: bash --noprofile --norc -eo pipefail -x {0}
      if: failure() && github.event_name == 'pull_request'
      run: |
        # Enable tmate only in the Rook fork, where the USE_TMATE secret is set in the repo, or if the action is re-run
        if [ "$GITHUB_REPOSITORY_OWNER" = "rook" ] || [ -n "${{ inputs.use-tmate }}" ] || [ "$GITHUB_RUN_ATTEMPT" -gt 1 ]; then
          echo USE_TMATE=1 >> $GITHUB_ENV
        fi
        echo "${{ inputs.timeout-minutes }}"

    - name: set up tmate session for debugging
      if: failure() && env.USE_TMATE
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: "${{ inputs.timeout-minutes }}"
